### ISSUE TITLE
Freezes while loading GTNH 2.7.0 beta

### ISSUE THREAD

**Issue by ghost** [ah-OOG-ah/GregtorioOverlays#12]
Gets stuck at 33%: Pre Initialization: loading Iguana Tinker Tweaks

Live log ends at: [12:11:57] [Sound Library Loader/INFO]: Sound engine started

[latest.log](https://github.com/user-attachments/files/17117536/latest.log)
[fml-client-latest.log](https://github.com/user-attachments/files/17117537/fml-client-latest.log)

**Comment by ah-OOG-ah** [comment]
Same issue as #11 , will be fixed soon
