### ISSUE TITLE
Does not work on GTNH 2.7.0 Beta. 

### ISSUE THREAD

**Issue by talianagisan** [ah-OOG-ah/GregtorioOverlays#14]
Greetings. I've been playing GTNH on a server with my friend using the beta branch. We have gotten to the point where we polluted ourselves like idiots but the map overlay shows 0 and the button in journey map shows nothing. I assume this is beta issues but felt i should report it. We do not have the mod in the servers mod folder so if that's required tell me. Love the name Gregtorio tho.

**Comment by ah-OOG-ah** [comment]
It is required serverside to be functional, at least for now. It doesn't block the connection so you can use the same instance to connect to servers not running it. Add another comment if it's still broken when installed server-side and I'll reopen it.

**Comment by talianagisan** [comment]
It unfortunately still did not work or i am dumb and forgot something, all possible. Here is the logs for both. 
[fml-client-latest.log](https://github.com/user-attachments/files/17909158/fml-client-latest.log)
[fml-server-latest.log](https://github.com/user-attachments/files/17909159/fml-server-latest.log)

**Comment by ah-OOG-ah** [comment]
Odd, I'll look into it. Just to be sure, both the client and the server have pollution enabled, right?

**Comment by talianagisan** [comment]
That is correct. We are running vanilla configs which have it enabled for both. I can tell its on the server for sure as i cant see near my blast furnaces.
