### ISSUE TITLE
Missing requirement 'navigator'

### ISSUE THREAD

**Issue by meatmobile** [ah-OOG-ah/GregtorioOverlays#9]
What it says on the tin. According to my log, this mod requires something called 'navigator' when I add it to GTNH but I have no idea what mod that's supposed to be. What is it and where do I download it?

**Comment by meatmobile** [comment]
I'm just going to uninstall this and not bother given how unlikely it is that a 1.7.10 mod is going to be fixed. I have all the listed requirements.

**Comment by Ren-Pen** [comment]
Seems need add this mod.
https://github.com/GTNewHorizons/Navigator

**Comment by Ren-Pen** [comment]
Ohh, that seems not work....

**Comment by ah-OOG-ah** [comment]
> What it says on the tin. According to my log, this mod requires something called 'navigator' when I add it to GTNH but I have no idea what mod that's supposed to be. What is it and where do I download it?

Are you on 2.6.1 or a nightly version? 1.0.1 should work in the latest nightlies - for 2.6.1, pick 0.3.1 instead, as it predates Navigator. If you're still having issues, reopen this and post your log.
